# puerto donde correra el microservicio alertas
server.port=8087

# nombre de la aplicacion para identificar el microservicio
spring.application.name=alertas

# configuracion de conexion a mysql
spring.datasource.url=jdbc:mysql://localhost:3306/powerapp_alertas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# usuario de mysql
spring.datasource.username=root

# password de mysql
spring.datasource.password=

# driver mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate crea o actualiza las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# muestra consultas sql en consola
spring.jpa.show-sql=true

# dialecto mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
