server:
  port: 8081

spring:
  application:
    name: powerapp-autenticacion
  datasource:
    url: jdbc:mysql://localhost:3306/powerapp_autenticacion?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: powerapp2024SecretKeyMuyLargaParaQueSeaSegura123456
  expiration: 86400000
